import { Ionicons } from "@expo/vector-icons";
import * as Linking from "expo-linking";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";

const colors = { background: "#07131F", surface: "#0D2235", text: "#F2F7FB", muted: "#91A7B8", blue: "#2D9CFF", line: "#20435C" };

export default function AboutScreen() {
  return <ScreenContainer containerClassName="bg-[#07131F]" safeAreaClassName="bg-[#07131F]" edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  Back</Text></Pressable><View style={styles.hero}><View style={styles.logo}><Ionicons name="shield-checkmark" size={42} color={colors.blue} /></View><Text style={styles.title}>Heni Tech VPN</Text><Text style={styles.subtitle}>Independent manual VPN client</Text><Text style={styles.developer}>Developer: Heni John</Text></View><View style={styles.card}><Text style={styles.section}>Support and community</Text><Pressable style={styles.link} onPress={() => void Linking.openURL("https://t.me/Heni_Tech24")}><Ionicons name="paper-plane-outline" size={20} color={colors.blue} /><View style={styles.linkBody}><Text style={styles.linkTitle}>Heni Tech channel</Text><Text style={styles.linkDetail}>t.me/Heni_Tech24</Text></View><Ionicons name="open-outline" size={17} color={colors.muted} /></Pressable><Pressable style={styles.link} onPress={() => void Linking.openURL("https://t.me/heni_john")}><Ionicons name="person-outline" size={20} color={colors.blue} /><View style={styles.linkBody}><Text style={styles.linkTitle}>Developer Telegram</Text><Text style={styles.linkDetail}>t.me/heni_john</Text></View><Ionicons name="open-outline" size={17} color={colors.muted} /></Pressable></View><View style={styles.card}><Text style={styles.section}>Terms of use</Text><Text style={styles.terms}>Use only servers and accounts you own or are authorized to use. Heni Tech VPN does not provide a VPS, random server list, or a guarantee of availability. Keep credentials private and verify local laws and network policies before connecting.</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, gap: 14 }, back: { color: colors.blue, fontSize: 16, fontWeight: "700" }, hero: { alignItems: "center", paddingVertical: 20 }, logo: { width: 88, height: 88, borderRadius: 26, backgroundColor: "#092238", borderWidth: 1, borderColor: colors.line, alignItems: "center", justifyContent: "center", marginBottom: 16 }, title: { color: colors.text, fontSize: 28, fontWeight: "900" }, subtitle: { color: colors.muted, fontSize: 13, marginTop: 6 }, developer: { color: colors.blue, fontSize: 12, fontWeight: "800", marginTop: 12 }, card: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.line, padding: 15, gap: 12 }, section: { color: colors.text, fontSize: 15, fontWeight: "800" }, link: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 6 }, linkBody: { flex: 1 }, linkTitle: { color: colors.text, fontWeight: "800", fontSize: 13 }, linkDetail: { color: colors.muted, fontSize: 11, marginTop: 3 }, terms: { color: colors.muted, fontSize: 12, lineHeight: 19 },
});
