import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useAppState } from "@/lib/app-state";
import { protocolLabels } from "@/lib/domain";

const colors = { background: "#07131F", surface: "#0D2235", text: "#F2F7FB", muted: "#91A7B8", blue: "#2D9CFF", line: "#20435C", red: "#FF5C6C" };

export default function ProfilesScreen() {
  const { profiles, removeProfile } = useAppState();
  return <ScreenContainer containerClassName="bg-[#07131F]" safeAreaClassName="bg-[#07131F]"><View style={styles.container}><View style={styles.header}><View><Text style={styles.eyebrow}>MANUAL ONLY</Text><Text style={styles.title}>Profiles</Text></View><Pressable style={styles.add} onPress={() => router.push("/profile-editor")}><Ionicons name="add" size={23} color="#00182A" /></Pressable></View><Text style={styles.note}>Your servers only. Heni Tech VPN does not bundle a VPS or random server list.</Text>{profiles.length === 0 ? <View style={styles.empty}><Ionicons name="server-outline" size={34} color={colors.blue} /><Text style={styles.emptyTitle}>No manual profiles</Text><Text style={styles.emptyText}>Add the server details you own to create your first connection profile.</Text><Pressable style={styles.primary} onPress={() => router.push("/profile-editor")}><Text style={styles.primaryText}>Add manual profile</Text></Pressable></View> : <FlatList data={profiles} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <Pressable style={styles.card} onPress={() => router.push({ pathname: "/profile-editor", params: { id: item.id } })}><View style={styles.serverIcon}><Ionicons name="server-outline" size={21} color={colors.blue} /></View><View style={styles.body}><Text style={styles.name}>{item.name}</Text><Text style={styles.sub}>{protocolLabels[item.protocol]} · {item.host || "Host not set"}:{item.port}</Text></View><Pressable onPress={() => void removeProfile(item.id)} hitSlop={10}><Ionicons name="trash-outline" size={18} color={colors.red} /></Pressable></Pressable>} />}</View></ScreenContainer>;
}

const styles = StyleSheet.create({ container: { flex: 1, padding: 20 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, eyebrow: { color: "#5D88A4", fontSize: 11, letterSpacing: 2, fontWeight: "800" }, title: { color: colors.text, fontSize: 27, fontWeight: "800", marginTop: 4 }, add: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.blue, alignItems: "center", justifyContent: "center" }, note: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 14 }, empty: { marginTop: 80, alignItems: "center", backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 22, padding: 26 }, emptyTitle: { color: colors.text, fontSize: 17, fontWeight: "800", marginTop: 12 }, emptyText: { color: colors.muted, textAlign: "center", lineHeight: 19, marginTop: 8 }, primary: { marginTop: 18, backgroundColor: colors.blue, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 13 }, primaryText: { color: "#00182A", fontWeight: "800" }, list: { gap: 10, paddingTop: 18, paddingBottom: 20 }, card: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.surface, borderRadius: 17, borderWidth: 1, borderColor: colors.line, padding: 14 }, serverIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: "#092238", alignItems: "center", justifyContent: "center" }, body: { flex: 1 }, name: { color: colors.text, fontWeight: "800", fontSize: 14 }, sub: { color: colors.muted, fontSize: 11, marginTop: 5 },
});
